global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: "demo"
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002
